### ISSUE TITLE
Enable setting non-characterized motor controllers to Brake mode

### ISSUE THREAD

**Issue by jlmcmchl** [wpilibsuite/sysid#198]
In many recent years, many teams have designed or used mechanisms where multiple joints are in use (eg. wrist on elevator, wrist on arm, swerve - lock rotation when calibrating drive, lock drive when calibrating rotation). In all of those systems, if the connected mechanism coasts, results will be less accurately measured, or present a safety hazard.

Another use case I would like for this is in characterizing heading control on a swerve drive. Now - because sysid works with voltage and does not support abstractions like controlling individual swerve modules, this may not be the right fit for this project. Nonetheless, any guidance or advice on tuning Swerve heading controllers would be much appreciated.

I propose that sysid allows users to provide a list of mapped motor controllers, separate from the characterized controller list, in which all would be configured in Brake Mode.

In past years, I have solved this by making changes to the generated code in frc-characterization, but seeing as sysid does not have a generation step, this is not a viable alternative. I would like to be able to use sysid in the coming year as it provides better characterization results based on early testing.

**Comment by calcmogul** [comment]
## On making motors use brake mode

> In many recent years, many teams have designed or used mechanisms where multiple joints are in use (eg. wrist on elevator, wrist on arm, swerve - lock rotation when calibrating drive, lock drive when calibrating rotation). In all of those systems, if the connected mechanism coasts, results will be less accurately measured, or present a safety hazard.
> ...
> I propose that sysid allows users to provide a list of mapped motor controllers, separate from the characterized controller list, in which all would be configured in Brake Mode.

SysId doesn't do anything to motors that aren't specified in the UI, so you could set the other motors to brake mode yourself before the test using the REV or CTRE client. If I recall correctly, the motor controllers retain their brake/coast setting between  power cycles.

For doing system ID on module heading, just use "simple motor" mode on one stationary module. One you have the heading controllers tuned, tuning the velocity and chassis heading controllers becomes possible with a separate project. I'll get into how that can be done later, but it won't be convenient.

## Design rationale

For context, SysId is designed for system identification of elevators, single-jointed arms, flywheels, and differential drives. It working on other mechanisms and drivebases like swerve is a coincidence. Not that you're asking for this exactly, but I think first-class support for swerve drives is out of scope because it would take a lot more effort to add feedback control into SysId for various swerve drive configurations.

> In past years, I have solved this by making changes to the generated code in frc-characterization, but seeing as sysid does not have a generation step, this is not a viable alternative.

We decided to precompile the robot programs rather than generate them to eliminate a class of issues users were hitting with regard to misconfigured development environments. It also simplified the application itself because we don't have to store all the gradle build system files and vendordep jsons as resources within the executable; doing that in C++ is hard.

Given those limitations, that begs the question of why we picked C++ and Dear ImGui for the new tool. We did that because:

1. We could reuse allwpilib's ImGui infrastructure
2. Interactive GUIs are easier to write in ImGui than JavaFX
3. We could reuse parts of wpimath for the analysis steps
4. Our developers are much more familiar with C++ than Java

## Adding logging to an existing swerve project

We also made the robot program use C++. frc-char used Java projects, but it produced noisier data since the scheduling was less deterministic. We also wanted to sample data every 5 ms to better capture acceleration events on flywheels, but Java can't achieve that fast of a sample rate due to the GC. We wrote a [C++-only library](https://github.com/wpilibsuite/sysid/tree/main/sysid-library/src/main) to address these more stringent logging needs.

We could look into publishing that library as a vendordep, but that doesn't help the majority of teams that use Java, and porting to Java defeats the purpose. We'd also have to document its integration and usage better, but we should probably do that anyway.

**Comment by calcmogul** [comment]
For more complex systems like swerve drives or double-jointed arms, there's more powerful/general system identification schemes that can be used by recording the (noisy) state measurements and input voltages. It requires a least-squares solver. The vector form I think the standard form would work as long as the matrices are expanded to make  for a sparse
